MAX_LENGTH_NAME_TAGS = 32
MAX_LENGTH_SLUG_TAGS = 32
MAX_LENGTH_NAME_INGR = 128
MAX_LENGTH_MEAS_UNIT = 64
MAX_LENGTH_NAME_RESIPES = 256
MAX_LENGTH_SHORT_LINK = 10
MIN_INGREDIENTS_AMOUNT = 1
MIN_COOKING_TIME = 1
