MAX_LENGTH_NAME = 256
MAX_LENGTH_SLUG = 50
MAX_LENGTH_EMAIL = 254
MAX_LENGTH_USERNAME = 150
MAX_LENGTH_CONFIRMATION_CODE = 6
MAX_LENGTH_ROLE = 10
MIN_INGREDIENTS_AMOUNT = 1
MIN_COOKING_TIME = 1

MAX_VALUE_SCORE = 10
