volumes:
  pg_data:
  static:
  media:
  
services:

  db:
    image: postgres:13.10
    container_name: foodgram-db
    env_file: .env
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    container_name: foodgram-frontend
    image: evgenyfil/foodgram_frontend:latest
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  backend:
    container_name: foodgram-backend
    image: evgenyfil/foodgram_backend:latest
    env_file: .env
    restart: unless-stopped
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
      - frontend
      
  gateway:
    container_name: foodgram-gateway
    image: evgenyfil/foodgram_gateway:latest
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
