# Generated by Django 4.2.19 on 2025-02-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_subscription_subscription_unique_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
