# Generated by Django 4.2.19 on 2025-02-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipes_is_favorited_recipes_is_in_shopping_cart'),
        ('myprofile', '0004_alter_subscription_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='recipes.recipes'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='shopping_cart_recipes',
            field=models.ManyToManyField(blank=True, related_name='in_shopping_cart', to='recipes.recipes'),
        ),
    ]
