# Generated by Django 4.2.19 on 2025-03-19 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipes_options_recipes_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='is_in_shopping_cart',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Время приготовления, мин'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredients',
            unique_together={('name', 'measurement_unit')},
        ),
    ]
