# Generated by Django 4.2.19 on 2025-03-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipeingredients_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredients',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredients',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='ingredients',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredients',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='unique_recipe_ingredients'),
        ),
    ]
